export const CATEGORIES: Category[] = [
  {
    id: 'appetizers',
    nameAr: 'مقدمات مغربية',
    nameFr: 'Entrées Marocaines',
    icon: 'chef-hat',
  },
  {
    id: 'tagines',
    nameAr: 'طواجين',
    nameFr: 'Tagines',
    icon: 'pot-steam',
  },
  {
    id: 'couscous',
    nameAr: 'كسكس',
    nameFr: 'Couscous',
    icon: 'wheat',
  },
  {
    id: 'pastillas',
    nameAr: 'بسطيلات',
    nameFr: 'Pastillas',
    icon: 'layer-group',
  },
  {
    id: 'soups',
    nameAr: 'شوربة',
    nameFr: 'Soupe',
    icon: 'bowl-food',
  },
  {
    id: 'drinks',
    nameAr: 'مشروبات',
    nameFr: 'Boissons',
    icon: 'coffee',
  },
];

export const DISHES: Dish[] = [
  {
    id: 'harira',
    nameAr: 'حريصة',
    nameFr: 'Harira',
    descriptionAr: 'شوربة تقليدية مغربية بتمر وشباكية، دافئة ومغذية',
    descriptionFr: 'Soupe traditionnelle marocaine avec dattes et Chebakia, chaude et nutritive',
    price: 25,
    category: 'soups',
    image: '/images/harira.jpg',
    isAvailable: true,
    isHalal: true,
  },
  {
    id: 'tajine-lamb-prunes',
    nameAr: 'طاجين لحم بالبرقوق',
    nameFr: 'Tajine d'Agneau aux Pruneaux',
    descriptionAr: 'طاجين لحم مغربي مع برقوق ولوز محمص، طعم أصيل ودافئ',
    descriptionFr: 'Agneau tagine with prunes and toasted almonds, flavor authentique et chaleureux',
    price: 85,
    category: 'tagines',
    image: '/images/tajine-lamb-prunes.jpg',
    isAvailable: true,
    isHalal: true,
  },
  {
    id: 'couscous-royal',
    nameAr: 'كسكس ملكي',
    nameFr: 'Couscous Royal',
    descriptionAr: 'كسكس بالماء الفوار، خضار طازجة، لحم دجاج، سمن مغربي',
    descriptionFr: 'Couscous à la vapeur, légumes frais, poulet, beurre marocain',
    price: 70,
    category: 'couscous',
    image: '/images/couscous-royal.jpg',
    isAvailable: true,
    isVegetarian: false,
  },
  {
    id: 'pastilla-chicken',
    nameAr: 'بسطيلة بالدجاج',
    nameFr: 'Pastilla au Poulet',
    descriptionAr: 'بسطيلة مغربية بطبقة عجين مقرمشة، دجاج، لوز، قرفة وسكر صقيل',
    descriptionFr: 'Pastilla au poulet avec amandes, cannelle et sucre glace',
    price: 95,
    category: 'pastillas',
    image: '/images/pastilla-chicken.jpg',
    isAvailable: true,
    isHalal: true,
  },
  {
    id: 'mint-tea',
    nameAr: 'شاي مغربي بالنعناع',
    nameFr: 'Thé à la Menthe',
    descriptionAr: 'شاي مغربي مع النعناع، يقدم في براد تقليدي مع سكر',
    descriptionFr: 'Thé marocain à la menthe, servi dans une théière traditionnelle',
    price: 15,
    category: 'drinks',
    image: '/images/mint-tea.jpg',
    isAvailable: true,
    isHalal: true,
  },
  {
    id: 'chebakia',
    nameAr: 'شباكية',
    nameFr: 'Chebakia',
    descriptionAr: 'حلوى مغربية تقليدية مقلية ومغلفة بالسمسم، تُقدم في المناسبات',
    descriptionFr: 'Chebakia traditionnelle, frit et enrobée de sésame, servie lors des fêtes',
    price: 20,
    category: 'drinks',
    image: '/images/chebakia.jpg',
    isAvailable: true,
    isVegetarian: true,
    isBestSeller: true,
  },
];

export const CART_ITEMS: CartItem[] = [];